Repository RallyHereInteractive/unreal-plugins, pull requests merged in 2024-06, with the labels that each got.

#239 BREAKING CHANGE - Convert GetLoggedInPlatform() to return a TOptional rather than Anon so it is correct when not logged in.
  Documentation/md/LocalPlayer.md
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_FriendSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_LocalPlayerSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_LocalPlayerSubsystem.h
Labels: bug, breaking change

#241 Add some additional safety around active session change in the bootstrapper.
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameInstanceBootstrappers.cpp
Labels: bug

#240 Rework for crash when instance data is deleted.
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameInstanceSessionSubsystem.cpp
Labels: bug

#221 Add basic support for prices composed of multiple different currencies
  Documentation/md/Inventory.md
  RallyHereDebugTool/Source/Private/RHDTW_Catalog.cpp
  RallyHereDebugTool/Source/Private/RHDTW_PlayerInventory.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_CatalogSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_PlayerInventory.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_CatalogSubsystem.h
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_PlayerInventory.h
Labels: enhancement

#232 Editor plugin login fix
  RallyHereDeveloperAPI/Source/RallyHereDeveloperAPI/Private/RallyHereDeveloperAPIAuthContext.cpp
  RallyHereDeveloperAPI/Source/RallyHereDeveloperAPI/Public/RallyHereDeveloperAPIAuthContext.h
  RallyHereIntegration/Source/RallyHereEditor/Private/RallyHereEditorLoginWidget.cpp
  RallyHereIntegration/Source/RallyHereEditor/Public/RH_DevIntegrationSettings.h
  RallyHereIntegration/Source/RallyHereEditor/Public/RallyHereEditorLoginWidget.h
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/dev-auth-context-header.mustache
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/dev-auth-context-source.mustache
Labels: enhancement

#244 BREAKING CHANGE - Mark IsReadyToJoinInstance() as final to cause any prior overrides of it to generate compile errors
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_GameInstanceSessionSubsystem.h
Labels: enhancement, breaking change

#245 Add sample gamemode base class that handles some common requirements for deployed dedicated servers
  RallyHereIntegration/Source/RallyHereIntegration/Classes/RH_GameMode.h
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameMode.cpp
Labels: documentation, enhancement

#246 BREAKING CHANGE - Rework some aspects of session syncing and bootstrapping shutdown
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameInstanceBootstrappers.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameInstanceSessionSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_GameInstanceSessionSubsystem.h
Labels: bug, enhancement, breaking change

#248 Fix debug tool not toggling properly in some cases, and fix window docking in PIE not working properly
  RallyHereDebugTool/Source/Private/RallyHereDebugTool.cpp
  RallyHereDebugTool/Source/Private/RallyHereDebugToolModule.cpp
  RallyHereDebugTool/Source/Public/RallyHereDebugTool.h
Labels: bug

#247 First pass fix adding metadata flag to disable authorization retries on some requests, and set the flag for all login requests.
  RallyHereAPI/Source/RallyHereAPI/Private/AdAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/AuthAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/BlockedV1API.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/BlockedV2API.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/CatalogAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/ConfigAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/ConfigurationV1API.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/CustomAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/DeserterAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/EntitlementsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/EnvironmentAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/EventsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/FriendsV1API.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/FriendsV2API.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/InstanceNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/InventoryAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/KeyClaimsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/KeyEntitlementsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/MarketingAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/MatchAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PlayerIdNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PlayerNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PresenceAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PresenceAdminAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/QueuesAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/RallyHereAPIAuthContext.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/RallyHereAPIBaseModel.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/RankAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/RegionsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/RemoteFileAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/ReportsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/SessionAuditAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/SessionsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/SettingsAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/TimeAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/UsersAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/VOIPAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Public/RallyHereAPIAuthContext.h
  RallyHereAPI/Source/RallyHereAPI/Public/RallyHereAPIBaseModel.h
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_BootstrappingHelpers.h
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_LocalPlayerLoginSubsystem.cpp
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/api-source.mustache
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/auth-context-header.mustache
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/auth-context-source.mustache
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/model-base-header.mustache
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/model-base-source.mustache
Labels: bug

#250 Fix uninitialized request metadata flag
  RallyHereAPI/Source/RallyHereAPI/Public/RallyHereAPIBaseModel.h
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/model-base-header.mustache
Labels: bug

#251 Make friend update lambda captures use weak pointers for safety
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_FriendSubsystem.cpp
Labels: bug

#249 API Update: KickBeforeHint for mass logoff, remove Secret KVs support. Session new feature implementation for reserved state and instance request
  Documentation/md/Config.md
  Documentation/md/LocalPlayer.md
  Documentation/md/models/RHAPI_DeserterConfig.md
  Documentation/md/models/RHAPI_InstanceRequest.md
  Documentation/md/models/RHAPI_KVsResponseV2.md
  Documentation/md/models/RHAPI_MatchMakingProfileV2.md
  Documentation/md/models/RHAPI_MatchMakingRuleset.md
  Documentation/md/models/RHAPI_PlayerSession.md
  Documentation/md/models/RHAPI_QueueJoinRequest.md
  Documentation/md/models/RHAPI_SessionTemplate.md
  OnlineSubsystemHotfix/Source/Private/OnlineTitleFileHotfix.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/DeserterConfig.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/InstanceNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/InstanceRequest.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/KVsResponseV2.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/MatchMakingProfileV2.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/MatchMakingRuleset.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PlayerIdNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PlayerNotificationAPI.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/PlayerSession.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/QueueJoinRequest.cpp
  RallyHereAPI/Source/RallyHereAPI/Private/SessionTemplate.cpp
  RallyHereAPI/Source/RallyHereAPI/Public/DeserterConfig.h
  RallyHereAPI/Source/RallyHereAPI/Public/InstanceNotificationAPI.h
  RallyHereAPI/Source/RallyHereAPI/Public/InstanceRequest.h
  RallyHereAPI/Source/RallyHereAPI/Public/KVsResponseV2.h
  RallyHereAPI/Source/RallyHereAPI/Public/MatchMakingProfileV2.h
  RallyHereAPI/Source/RallyHereAPI/Public/MatchMakingRuleset.h
  RallyHereAPI/Source/RallyHereAPI/Public/PlayerIdNotificationAPI.h
  RallyHereAPI/Source/RallyHereAPI/Public/PlayerNotificationAPI.h
  RallyHereAPI/Source/RallyHereAPI/Public/PlayerSession.h
  RallyHereAPI/Source/RallyHereAPI/Public/QueueJoinRequest.h
  RallyHereAPI/Source/RallyHereAPI/Public/ReportsAPI.h
  RallyHereAPI/Source/RallyHereAPI/Public/SessionTemplate.h
  RallyHereDebugTool/Source/Private/RHDTW_Config.cpp
  RallyHereDebugTool/Source/Private/RHDTW_Session.cpp
  RallyHereDebugTool/Source/Private/RallyHereDebugToolSettings.h
  RallyHereDebugTool/Source/Public/RHDTW_Session.h
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_ConfigSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_LocalPlayerSessionSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_LocalPlayerSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_SessionHelpers.h
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_ConfigSubsystem.h
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_LocalPlayerSubsystem.h
Labels: enhancement, breaking change

#252 When using json serializer serialize arrays and objects directly without an identifier, rather than with an empty identifier
  RallyHereAPI/Source/RallyHereAPI/Public/RallyHereAPIHelpers.h
  openapi-generator-rh-cpp-unreal/src/main/resources/rh-cpp-ue4/helpers-header.mustache
Labels: bug

#253 Fix debug tool price display when using multicurrency prices
  RallyHereDebugTool/Source/Private/RHDTW_Catalog.cpp
Labels: bug

#254 Add settings (default on for Reactivate) for auto processing entitlements on reactivate and resume engine callbacks.
  Documentation/md/IntegrationSettings.md
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_GameInstanceSubsystem.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Private/RH_IntegrationSettings.cpp
  RallyHereIntegration/Source/RallyHereIntegration/Public/RH_IntegrationSettings.h
Labels: enhancement
